### ISSUE TITLE
forth2020 english version: shooter.r3 crashes in +shoot

### ISSUE THREAD

**Issue by Phi-Ho** [phreda4/r3d4#1]
Greetings,

Thank you for your r3d4 implementation.

I am following the tutorial in "forth2020 English version" on YouTube..

shooter.r3 crashes in:

:+shoot
  xb 1? ( drop ; ) drop
  yp 16 >> 14 + 'yb !
  100 30 + 'xb !
  ;

If the last line is commented out, no crash but no shoot either.

:+shoot
  xb 1? ( drop ; ) drop
  yp 16 >> 14 + 'yb !
|  100 30 + 'xb !
  ;
Please find attached my shooter.r3.

Regards,

phiho

[shooter.zip](https://github.com/phreda4/r3d4/files/5649582/shooter.zip)

**Comment by phreda4** [comment]
Hi Phiho !
Thank's you for use r3d4
the error happen in line 86
there are a missing drop

  xb sw >? ( 0 'xb ! drop ; ) drop

when the stack have unbalance behavior, the can crash!!
you can use the debugger for searching what's happen.. f2 in the editor.. put the cursor in the critical part and hit f7/f8 for advance.

Best Regards
Pablo

**Comment by Phi-Ho** [comment]
Hi Pablo,

Thanks for the tips.

Now it can shoot but crashes before hitting UFO.
I like to debug hit??

Would you please explain what each keys (TAB F1 F2 F3 F6 F7 F8) does in the
debugger
What does A:0 B:0 mean

Are there any other development tools besides the editor and debugger?
Can r3 use the object produced by fasm?

By the way, is there some documentation somewhere?
I would like to learn more about r3.

Thanks again,

phiho

**Comment by phreda4** [comment]
line 68 is - not =
  xa 16 >> 10 - 'xx !

line 69 be
 0 'xs !

line 77, one more drop
  20 >?   ( drop ; ) drop

The debugger is in progress but usable.
f1 play full (not very usefull for now)
f2 play to cursor... go to word and f2 then stop when came here
f3 analysis..in early stage.. not usable for now
f6 view screen
f7 step go to inner definition
f8 step over definition
tab, enter in interactive mode, in early stage too
you have a old version (now I remove A and B, but this are auxiliari register for traverse memory
you can use the word TRACE.. including the r3/lib/trace.r3 library and the stop the execution and see the stack, or dump memory with dump
for now only generate fasm output, not the reverse but who know?
there are a documentation in doc/ folder, very basic because R3 is the sucessor of R4.. you can found much more information about this lang in
https://github.com/phreda4/r4
and in
https://phreda4.github.io/

if you have facebook I can invite to the forth group, send me a email to pabloreda@gmail.com!!

Best, Regards
Pablo
